/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppKnowledgesRouteImport } from './routes/app/knowledges'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authInviteRouteImport } from './routes/(auth)/invite'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AdminChatRouteRouteImport } from './routes/admin/chat/route'
import { Route as AdminMcpsIndexRouteImport } from './routes/admin/mcps/index'
import { Route as AdminKnowledgesIndexRouteImport } from './routes/admin/knowledges/index'
import { Route as AdminGlobalConfigIndexRouteImport } from './routes/admin/global-config/index'
import { Route as AdminDashboardsIndexRouteImport } from './routes/admin/dashboards/index'
import { Route as AdminChatIndexRouteImport } from './routes/admin/chat/index'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin/agents/index'
import { Route as AdminDashboardsIdRouteImport } from './routes/admin/dashboards/$id'
import { Route as AdminChatIdRouteImport } from './routes/admin/chat/$id'
import { Route as AdminAgentsOrchestratorIndexRouteImport } from './routes/admin/agents/orchestrator/index'
import { Route as AdminAgentsGardenIndexRouteImport } from './routes/admin/agents/garden/index'
import { Route as AdminAgentsOrchestratorIdRouteImport } from './routes/admin/agents/orchestrator/$id'
import { Route as AdminAgentsGardenIdRouteImport } from './routes/admin/agents/garden/$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgesRoute = AppKnowledgesRouteImport.update({
  id: '/knowledges',
  path: '/knowledges',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authInviteRoute = authInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminChatRouteRoute = AdminChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMcpsIndexRoute = AdminMcpsIndexRouteImport.update({
  id: '/mcps/',
  path: '/mcps/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKnowledgesIndexRoute = AdminKnowledgesIndexRouteImport.update({
  id: '/knowledges/',
  path: '/knowledges/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGlobalConfigIndexRoute = AdminGlobalConfigIndexRouteImport.update({
  id: '/global-config/',
  path: '/global-config/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardsIndexRoute = AdminDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatIndexRoute = AdminChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminChatRouteRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardsIdRoute = AdminDashboardsIdRouteImport.update({
  id: '/dashboards/$id',
  path: '/dashboards/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatIdRoute = AdminChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminChatRouteRoute,
} as any)
const AdminAgentsOrchestratorIndexRoute =
  AdminAgentsOrchestratorIndexRouteImport.update({
    id: '/agents/orchestrator/',
    path: '/agents/orchestrator/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAgentsGardenIndexRoute = AdminAgentsGardenIndexRouteImport.update({
  id: '/agents/garden/',
  path: '/agents/garden/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgentsOrchestratorIdRoute =
  AdminAgentsOrchestratorIdRouteImport.update({
    id: '/agents/orchestrator/$id',
    path: '/agents/orchestrator/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAgentsGardenIdRoute = AdminAgentsGardenIdRouteImport.update({
  id: '/agents/garden/$id',
  path: '/agents/garden/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/admin/chat': typeof AdminChatRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/invite': typeof authInviteRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/tags': typeof AdminTagsRoute
  '/app/chat': typeof AppChatRoute
  '/app/knowledges': typeof AppKnowledgesRoute
  '/app/': typeof AppIndexRoute
  '/admin/chat/$id': typeof AdminChatIdRoute
  '/admin/dashboards/$id': typeof AdminDashboardsIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/chat/': typeof AdminChatIndexRoute
  '/admin/dashboards/': typeof AdminDashboardsIndexRoute
  '/admin/global-config/': typeof AdminGlobalConfigIndexRoute
  '/admin/knowledges/': typeof AdminKnowledgesIndexRoute
  '/admin/mcps/': typeof AdminMcpsIndexRoute
  '/admin/agents/garden/$id': typeof AdminAgentsGardenIdRoute
  '/admin/agents/orchestrator/$id': typeof AdminAgentsOrchestratorIdRoute
  '/admin/agents/garden/': typeof AdminAgentsGardenIndexRoute
  '/admin/agents/orchestrator/': typeof AdminAgentsOrchestratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/invite': typeof authInviteRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/tags': typeof AdminTagsRoute
  '/app/chat': typeof AppChatRoute
  '/app/knowledges': typeof AppKnowledgesRoute
  '/app': typeof AppIndexRoute
  '/admin/chat/$id': typeof AdminChatIdRoute
  '/admin/dashboards/$id': typeof AdminDashboardsIdRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/chat': typeof AdminChatIndexRoute
  '/admin/dashboards': typeof AdminDashboardsIndexRoute
  '/admin/global-config': typeof AdminGlobalConfigIndexRoute
  '/admin/knowledges': typeof AdminKnowledgesIndexRoute
  '/admin/mcps': typeof AdminMcpsIndexRoute
  '/admin/agents/garden/$id': typeof AdminAgentsGardenIdRoute
  '/admin/agents/orchestrator/$id': typeof AdminAgentsOrchestratorIdRoute
  '/admin/agents/garden': typeof AdminAgentsGardenIndexRoute
  '/admin/agents/orchestrator': typeof AdminAgentsOrchestratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/admin/chat': typeof AdminChatRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/invite': typeof authInviteRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/tags': typeof AdminTagsRoute
  '/app/chat': typeof AppChatRoute
  '/app/knowledges': typeof AppKnowledgesRoute
  '/app/': typeof AppIndexRoute
  '/admin/chat/$id': typeof AdminChatIdRoute
  '/admin/dashboards/$id': typeof AdminDashboardsIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/chat/': typeof AdminChatIndexRoute
  '/admin/dashboards/': typeof AdminDashboardsIndexRoute
  '/admin/global-config/': typeof AdminGlobalConfigIndexRoute
  '/admin/knowledges/': typeof AdminKnowledgesIndexRoute
  '/admin/mcps/': typeof AdminMcpsIndexRoute
  '/admin/agents/garden/$id': typeof AdminAgentsGardenIdRoute
  '/admin/agents/orchestrator/$id': typeof AdminAgentsOrchestratorIdRoute
  '/admin/agents/garden/': typeof AdminAgentsGardenIndexRoute
  '/admin/agents/orchestrator/': typeof AdminAgentsOrchestratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/chat'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/api-keys'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/tags'
    | '/app/chat'
    | '/app/knowledges'
    | '/app/'
    | '/admin/chat/$id'
    | '/admin/dashboards/$id'
    | '/admin/agents/'
    | '/admin/chat/'
    | '/admin/dashboards/'
    | '/admin/global-config/'
    | '/admin/knowledges/'
    | '/admin/mcps/'
    | '/admin/agents/garden/$id'
    | '/admin/agents/orchestrator/$id'
    | '/admin/agents/garden/'
    | '/admin/agents/orchestrator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/api-keys'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/tags'
    | '/app/chat'
    | '/app/knowledges'
    | '/app'
    | '/admin/chat/$id'
    | '/admin/dashboards/$id'
    | '/admin/agents'
    | '/admin/chat'
    | '/admin/dashboards'
    | '/admin/global-config'
    | '/admin/knowledges'
    | '/admin/mcps'
    | '/admin/agents/garden/$id'
    | '/admin/agents/orchestrator/$id'
    | '/admin/agents/garden'
    | '/admin/agents/orchestrator'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/admin'
    | '/app'
    | '/admin/chat'
    | '/(auth)/forgot-password'
    | '/(auth)/invite'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/admin/api-keys'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/tags'
    | '/app/chat'
    | '/app/knowledges'
    | '/app/'
    | '/admin/chat/$id'
    | '/admin/dashboards/$id'
    | '/admin/agents/'
    | '/admin/chat/'
    | '/admin/dashboards/'
    | '/admin/global-config/'
    | '/admin/knowledges/'
    | '/admin/mcps/'
    | '/admin/agents/garden/$id'
    | '/admin/agents/orchestrator/$id'
    | '/admin/agents/garden/'
    | '/admin/agents/orchestrator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/knowledges': {
      id: '/app/knowledges'
      path: '/knowledges'
      fullPath: '/app/knowledges'
      preLoaderRoute: typeof AppKnowledgesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/invite': {
      id: '/(auth)/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof authInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mcps/': {
      id: '/admin/mcps/'
      path: '/mcps'
      fullPath: '/admin/mcps/'
      preLoaderRoute: typeof AdminMcpsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/knowledges/': {
      id: '/admin/knowledges/'
      path: '/knowledges'
      fullPath: '/admin/knowledges/'
      preLoaderRoute: typeof AdminKnowledgesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/global-config/': {
      id: '/admin/global-config/'
      path: '/global-config'
      fullPath: '/admin/global-config/'
      preLoaderRoute: typeof AdminGlobalConfigIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboards/': {
      id: '/admin/dashboards/'
      path: '/dashboards'
      fullPath: '/admin/dashboards/'
      preLoaderRoute: typeof AdminDashboardsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chat/': {
      id: '/admin/chat/'
      path: '/'
      fullPath: '/admin/chat/'
      preLoaderRoute: typeof AdminChatIndexRouteImport
      parentRoute: typeof AdminChatRouteRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboards/$id': {
      id: '/admin/dashboards/$id'
      path: '/dashboards/$id'
      fullPath: '/admin/dashboards/$id'
      preLoaderRoute: typeof AdminDashboardsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chat/$id': {
      id: '/admin/chat/$id'
      path: '/$id'
      fullPath: '/admin/chat/$id'
      preLoaderRoute: typeof AdminChatIdRouteImport
      parentRoute: typeof AdminChatRouteRoute
    }
    '/admin/agents/orchestrator/': {
      id: '/admin/agents/orchestrator/'
      path: '/agents/orchestrator'
      fullPath: '/admin/agents/orchestrator/'
      preLoaderRoute: typeof AdminAgentsOrchestratorIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents/garden/': {
      id: '/admin/agents/garden/'
      path: '/agents/garden'
      fullPath: '/admin/agents/garden/'
      preLoaderRoute: typeof AdminAgentsGardenIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents/orchestrator/$id': {
      id: '/admin/agents/orchestrator/$id'
      path: '/agents/orchestrator/$id'
      fullPath: '/admin/agents/orchestrator/$id'
      preLoaderRoute: typeof AdminAgentsOrchestratorIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents/garden/$id': {
      id: '/admin/agents/garden/$id'
      path: '/agents/garden/$id'
      fullPath: '/admin/agents/garden/$id'
      preLoaderRoute: typeof AdminAgentsGardenIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authInviteRoute: typeof authInviteRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authInviteRoute: authInviteRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AdminChatRouteRouteChildren {
  AdminChatIdRoute: typeof AdminChatIdRoute
  AdminChatIndexRoute: typeof AdminChatIndexRoute
}

const AdminChatRouteRouteChildren: AdminChatRouteRouteChildren = {
  AdminChatIdRoute: AdminChatIdRoute,
  AdminChatIndexRoute: AdminChatIndexRoute,
}

const AdminChatRouteRouteWithChildren = AdminChatRouteRoute._addFileChildren(
  AdminChatRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminChatRouteRoute: typeof AdminChatRouteRouteWithChildren
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminDashboardsIdRoute: typeof AdminDashboardsIdRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
  AdminDashboardsIndexRoute: typeof AdminDashboardsIndexRoute
  AdminGlobalConfigIndexRoute: typeof AdminGlobalConfigIndexRoute
  AdminKnowledgesIndexRoute: typeof AdminKnowledgesIndexRoute
  AdminMcpsIndexRoute: typeof AdminMcpsIndexRoute
  AdminAgentsGardenIdRoute: typeof AdminAgentsGardenIdRoute
  AdminAgentsOrchestratorIdRoute: typeof AdminAgentsOrchestratorIdRoute
  AdminAgentsGardenIndexRoute: typeof AdminAgentsGardenIndexRoute
  AdminAgentsOrchestratorIndexRoute: typeof AdminAgentsOrchestratorIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminChatRouteRoute: AdminChatRouteRouteWithChildren,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminDashboardsIdRoute: AdminDashboardsIdRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
  AdminDashboardsIndexRoute: AdminDashboardsIndexRoute,
  AdminGlobalConfigIndexRoute: AdminGlobalConfigIndexRoute,
  AdminKnowledgesIndexRoute: AdminKnowledgesIndexRoute,
  AdminMcpsIndexRoute: AdminMcpsIndexRoute,
  AdminAgentsGardenIdRoute: AdminAgentsGardenIdRoute,
  AdminAgentsOrchestratorIdRoute: AdminAgentsOrchestratorIdRoute,
  AdminAgentsGardenIndexRoute: AdminAgentsGardenIndexRoute,
  AdminAgentsOrchestratorIndexRoute: AdminAgentsOrchestratorIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppKnowledgesRoute: typeof AppKnowledgesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppKnowledgesRoute: AppKnowledgesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
