/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainTagsRouteImport } from './routes/(main)/tags'
import { Route as mainMembersRouteImport } from './routes/(main)/members'
import { Route as mainLogsRouteImport } from './routes/(main)/logs'
import { Route as mainDashboardRouteImport } from './routes/(main)/dashboard'
import { Route as mainAuditLogsRouteImport } from './routes/(main)/audit-logs'
import { Route as mainApiKeysRouteImport } from './routes/(main)/api-keys'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authInviteRouteImport } from './routes/(auth)/invite'
import { Route as mainChatRouteRouteImport } from './routes/(main)/chat/route'
import { Route as mainMcpsIndexRouteImport } from './routes/(main)/mcps/index'
import { Route as mainKnowledgesIndexRouteImport } from './routes/(main)/knowledges/index'
import { Route as mainGlobalConfigIndexRouteImport } from './routes/(main)/global-config/index'
import { Route as mainChatIndexRouteImport } from './routes/(main)/chat/index'
import { Route as mainAgentsIndexRouteImport } from './routes/(main)/agents/index'
import { Route as mainChatIdRouteImport } from './routes/(main)/chat/$id'
import { Route as mainAgentsOrchestratorIndexRouteImport } from './routes/(main)/agents/orchestrator/index'
import { Route as mainAgentsGardenIndexRouteImport } from './routes/(main)/agents/garden/index'
import { Route as mainAgentsOrchestratorIdRouteImport } from './routes/(main)/agents/orchestrator/$id'
import { Route as mainAgentsGardenIdRouteImport } from './routes/(main)/agents/garden/$id'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainTagsRoute = mainTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMembersRoute = mainMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLogsRoute = mainLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuditLogsRoute = mainAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainApiKeysRoute = mainApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authInviteRoute = authInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => authRouteRoute,
} as any)
const mainChatRouteRoute = mainChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMcpsIndexRoute = mainMcpsIndexRouteImport.update({
  id: '/mcps/',
  path: '/mcps/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainKnowledgesIndexRoute = mainKnowledgesIndexRouteImport.update({
  id: '/knowledges/',
  path: '/knowledges/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainGlobalConfigIndexRoute = mainGlobalConfigIndexRouteImport.update({
  id: '/global-config/',
  path: '/global-config/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainChatIndexRoute = mainChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainChatRouteRoute,
} as any)
const mainAgentsIndexRoute = mainAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainChatIdRoute = mainChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => mainChatRouteRoute,
} as any)
const mainAgentsOrchestratorIndexRoute =
  mainAgentsOrchestratorIndexRouteImport.update({
    id: '/agents/orchestrator/',
    path: '/agents/orchestrator/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainAgentsGardenIndexRoute = mainAgentsGardenIndexRouteImport.update({
  id: '/agents/garden/',
  path: '/agents/garden/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAgentsOrchestratorIdRoute =
  mainAgentsOrchestratorIdRouteImport.update({
    id: '/agents/orchestrator/$id',
    path: '/agents/orchestrator/$id',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainAgentsGardenIdRoute = mainAgentsGardenIdRouteImport.update({
  id: '/agents/garden/$id',
  path: '/agents/garden/$id',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof mainChatRouteRouteWithChildren
  '/invite': typeof authInviteRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api-keys': typeof mainApiKeysRoute
  '/audit-logs': typeof mainAuditLogsRoute
  '/dashboard': typeof mainDashboardRoute
  '/logs': typeof mainLogsRoute
  '/members': typeof mainMembersRoute
  '/tags': typeof mainTagsRoute
  '/chat/$id': typeof mainChatIdRoute
  '/agents/': typeof mainAgentsIndexRoute
  '/chat/': typeof mainChatIndexRoute
  '/global-config/': typeof mainGlobalConfigIndexRoute
  '/knowledges/': typeof mainKnowledgesIndexRoute
  '/mcps/': typeof mainMcpsIndexRoute
  '/agents/garden/$id': typeof mainAgentsGardenIdRoute
  '/agents/orchestrator/$id': typeof mainAgentsOrchestratorIdRoute
  '/agents/garden/': typeof mainAgentsGardenIndexRoute
  '/agents/orchestrator/': typeof mainAgentsOrchestratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof authInviteRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api-keys': typeof mainApiKeysRoute
  '/audit-logs': typeof mainAuditLogsRoute
  '/dashboard': typeof mainDashboardRoute
  '/logs': typeof mainLogsRoute
  '/members': typeof mainMembersRoute
  '/tags': typeof mainTagsRoute
  '/chat/$id': typeof mainChatIdRoute
  '/agents': typeof mainAgentsIndexRoute
  '/chat': typeof mainChatIndexRoute
  '/global-config': typeof mainGlobalConfigIndexRoute
  '/knowledges': typeof mainKnowledgesIndexRoute
  '/mcps': typeof mainMcpsIndexRoute
  '/agents/garden/$id': typeof mainAgentsGardenIdRoute
  '/agents/orchestrator/$id': typeof mainAgentsOrchestratorIdRoute
  '/agents/garden': typeof mainAgentsGardenIndexRoute
  '/agents/orchestrator': typeof mainAgentsOrchestratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/chat': typeof mainChatRouteRouteWithChildren
  '/(auth)/invite': typeof authInviteRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(main)/api-keys': typeof mainApiKeysRoute
  '/(main)/audit-logs': typeof mainAuditLogsRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(main)/logs': typeof mainLogsRoute
  '/(main)/members': typeof mainMembersRoute
  '/(main)/tags': typeof mainTagsRoute
  '/(main)/chat/$id': typeof mainChatIdRoute
  '/(main)/agents/': typeof mainAgentsIndexRoute
  '/(main)/chat/': typeof mainChatIndexRoute
  '/(main)/global-config/': typeof mainGlobalConfigIndexRoute
  '/(main)/knowledges/': typeof mainKnowledgesIndexRoute
  '/(main)/mcps/': typeof mainMcpsIndexRoute
  '/(main)/agents/garden/$id': typeof mainAgentsGardenIdRoute
  '/(main)/agents/orchestrator/$id': typeof mainAgentsOrchestratorIdRoute
  '/(main)/agents/garden/': typeof mainAgentsGardenIndexRoute
  '/(main)/agents/orchestrator/': typeof mainAgentsOrchestratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/invite'
    | '/login'
    | '/signup'
    | '/api-keys'
    | '/audit-logs'
    | '/dashboard'
    | '/logs'
    | '/members'
    | '/tags'
    | '/chat/$id'
    | '/agents/'
    | '/chat/'
    | '/global-config/'
    | '/knowledges/'
    | '/mcps/'
    | '/agents/garden/$id'
    | '/agents/orchestrator/$id'
    | '/agents/garden/'
    | '/agents/orchestrator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/login'
    | '/signup'
    | '/api-keys'
    | '/audit-logs'
    | '/dashboard'
    | '/logs'
    | '/members'
    | '/tags'
    | '/chat/$id'
    | '/agents'
    | '/chat'
    | '/global-config'
    | '/knowledges'
    | '/mcps'
    | '/agents/garden/$id'
    | '/agents/orchestrator/$id'
    | '/agents/garden'
    | '/agents/orchestrator'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/(main)/chat'
    | '/(auth)/invite'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(main)/api-keys'
    | '/(main)/audit-logs'
    | '/(main)/dashboard'
    | '/(main)/logs'
    | '/(main)/members'
    | '/(main)/tags'
    | '/(main)/chat/$id'
    | '/(main)/agents/'
    | '/(main)/chat/'
    | '/(main)/global-config/'
    | '/(main)/knowledges/'
    | '/(main)/mcps/'
    | '/(main)/agents/garden/$id'
    | '/(main)/agents/orchestrator/$id'
    | '/(main)/agents/garden/'
    | '/(main)/agents/orchestrator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/tags': {
      id: '/(main)/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof mainTagsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/members': {
      id: '/(main)/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof mainMembersRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/logs': {
      id: '/(main)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof mainLogsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/audit-logs': {
      id: '/(main)/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof mainAuditLogsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/api-keys': {
      id: '/(main)/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof mainApiKeysRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/invite': {
      id: '/(auth)/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof authInviteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/chat': {
      id: '/(main)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof mainChatRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/mcps/': {
      id: '/(main)/mcps/'
      path: '/mcps'
      fullPath: '/mcps/'
      preLoaderRoute: typeof mainMcpsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/knowledges/': {
      id: '/(main)/knowledges/'
      path: '/knowledges'
      fullPath: '/knowledges/'
      preLoaderRoute: typeof mainKnowledgesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/global-config/': {
      id: '/(main)/global-config/'
      path: '/global-config'
      fullPath: '/global-config/'
      preLoaderRoute: typeof mainGlobalConfigIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/chat/': {
      id: '/(main)/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof mainChatIndexRouteImport
      parentRoute: typeof mainChatRouteRoute
    }
    '/(main)/agents/': {
      id: '/(main)/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof mainAgentsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/chat/$id': {
      id: '/(main)/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof mainChatIdRouteImport
      parentRoute: typeof mainChatRouteRoute
    }
    '/(main)/agents/orchestrator/': {
      id: '/(main)/agents/orchestrator/'
      path: '/agents/orchestrator'
      fullPath: '/agents/orchestrator/'
      preLoaderRoute: typeof mainAgentsOrchestratorIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/agents/garden/': {
      id: '/(main)/agents/garden/'
      path: '/agents/garden'
      fullPath: '/agents/garden/'
      preLoaderRoute: typeof mainAgentsGardenIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/agents/orchestrator/$id': {
      id: '/(main)/agents/orchestrator/$id'
      path: '/agents/orchestrator/$id'
      fullPath: '/agents/orchestrator/$id'
      preLoaderRoute: typeof mainAgentsOrchestratorIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/agents/garden/$id': {
      id: '/(main)/agents/garden/$id'
      path: '/agents/garden/$id'
      fullPath: '/agents/garden/$id'
      preLoaderRoute: typeof mainAgentsGardenIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authInviteRoute: typeof authInviteRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authInviteRoute: authInviteRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainChatRouteRouteChildren {
  mainChatIdRoute: typeof mainChatIdRoute
  mainChatIndexRoute: typeof mainChatIndexRoute
}

const mainChatRouteRouteChildren: mainChatRouteRouteChildren = {
  mainChatIdRoute: mainChatIdRoute,
  mainChatIndexRoute: mainChatIndexRoute,
}

const mainChatRouteRouteWithChildren = mainChatRouteRoute._addFileChildren(
  mainChatRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainChatRouteRoute: typeof mainChatRouteRouteWithChildren
  mainApiKeysRoute: typeof mainApiKeysRoute
  mainAuditLogsRoute: typeof mainAuditLogsRoute
  mainDashboardRoute: typeof mainDashboardRoute
  mainLogsRoute: typeof mainLogsRoute
  mainMembersRoute: typeof mainMembersRoute
  mainTagsRoute: typeof mainTagsRoute
  mainAgentsIndexRoute: typeof mainAgentsIndexRoute
  mainGlobalConfigIndexRoute: typeof mainGlobalConfigIndexRoute
  mainKnowledgesIndexRoute: typeof mainKnowledgesIndexRoute
  mainMcpsIndexRoute: typeof mainMcpsIndexRoute
  mainAgentsGardenIdRoute: typeof mainAgentsGardenIdRoute
  mainAgentsOrchestratorIdRoute: typeof mainAgentsOrchestratorIdRoute
  mainAgentsGardenIndexRoute: typeof mainAgentsGardenIndexRoute
  mainAgentsOrchestratorIndexRoute: typeof mainAgentsOrchestratorIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainChatRouteRoute: mainChatRouteRouteWithChildren,
  mainApiKeysRoute: mainApiKeysRoute,
  mainAuditLogsRoute: mainAuditLogsRoute,
  mainDashboardRoute: mainDashboardRoute,
  mainLogsRoute: mainLogsRoute,
  mainMembersRoute: mainMembersRoute,
  mainTagsRoute: mainTagsRoute,
  mainAgentsIndexRoute: mainAgentsIndexRoute,
  mainGlobalConfigIndexRoute: mainGlobalConfigIndexRoute,
  mainKnowledgesIndexRoute: mainKnowledgesIndexRoute,
  mainMcpsIndexRoute: mainMcpsIndexRoute,
  mainAgentsGardenIdRoute: mainAgentsGardenIdRoute,
  mainAgentsOrchestratorIdRoute: mainAgentsOrchestratorIdRoute,
  mainAgentsGardenIndexRoute: mainAgentsGardenIndexRoute,
  mainAgentsOrchestratorIndexRoute: mainAgentsOrchestratorIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
