/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainMembersRouteImport } from './routes/(main)/members'
import { Route as mainLogsRouteImport } from './routes/(main)/logs'
import { Route as mainDashboard2RouteImport } from './routes/(main)/dashboard2'
import { Route as mainApiKeysRouteImport } from './routes/(main)/api-keys'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainMcpsIndexRouteImport } from './routes/(main)/mcps/index'
import { Route as mainKnowledgesIndexRouteImport } from './routes/(main)/knowledges/index'
import { Route as mainAgentsIndexRouteImport } from './routes/(main)/agents/index'
import { Route as mainMcpsIdRouteImport } from './routes/(main)/mcps/$id'
import { Route as mainAgentsIdRouteImport } from './routes/(main)/agents/$id'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMembersRoute = mainMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLogsRoute = mainLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboard2Route = mainDashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainApiKeysRoute = mainApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const mainMcpsIndexRoute = mainMcpsIndexRouteImport.update({
  id: '/mcps/',
  path: '/mcps/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainKnowledgesIndexRoute = mainKnowledgesIndexRouteImport.update({
  id: '/knowledges/',
  path: '/knowledges/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAgentsIndexRoute = mainAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMcpsIdRoute = mainMcpsIdRouteImport.update({
  id: '/mcps/$id',
  path: '/mcps/$id',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAgentsIdRoute = mainAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api-keys': typeof mainApiKeysRoute
  '/dashboard2': typeof mainDashboard2Route
  '/logs': typeof mainLogsRoute
  '/members': typeof mainMembersRoute
  '/agents/$id': typeof mainAgentsIdRoute
  '/mcps/$id': typeof mainMcpsIdRoute
  '/agents/': typeof mainAgentsIndexRoute
  '/knowledges/': typeof mainKnowledgesIndexRoute
  '/mcps/': typeof mainMcpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api-keys': typeof mainApiKeysRoute
  '/dashboard2': typeof mainDashboard2Route
  '/logs': typeof mainLogsRoute
  '/members': typeof mainMembersRoute
  '/agents/$id': typeof mainAgentsIdRoute
  '/mcps/$id': typeof mainMcpsIdRoute
  '/agents': typeof mainAgentsIndexRoute
  '/knowledges': typeof mainKnowledgesIndexRoute
  '/mcps': typeof mainMcpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(main)/api-keys': typeof mainApiKeysRoute
  '/(main)/dashboard2': typeof mainDashboard2Route
  '/(main)/logs': typeof mainLogsRoute
  '/(main)/members': typeof mainMembersRoute
  '/(main)/agents/$id': typeof mainAgentsIdRoute
  '/(main)/mcps/$id': typeof mainMcpsIdRoute
  '/(main)/agents/': typeof mainAgentsIndexRoute
  '/(main)/knowledges/': typeof mainKnowledgesIndexRoute
  '/(main)/mcps/': typeof mainMcpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api-keys'
    | '/dashboard2'
    | '/logs'
    | '/members'
    | '/agents/$id'
    | '/mcps/$id'
    | '/agents/'
    | '/knowledges/'
    | '/mcps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api-keys'
    | '/dashboard2'
    | '/logs'
    | '/members'
    | '/agents/$id'
    | '/mcps/$id'
    | '/agents'
    | '/knowledges'
    | '/mcps'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(main)/api-keys'
    | '/(main)/dashboard2'
    | '/(main)/logs'
    | '/(main)/members'
    | '/(main)/agents/$id'
    | '/(main)/mcps/$id'
    | '/(main)/agents/'
    | '/(main)/knowledges/'
    | '/(main)/mcps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/members': {
      id: '/(main)/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof mainMembersRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/logs': {
      id: '/(main)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof mainLogsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard2': {
      id: '/(main)/dashboard2'
      path: '/dashboard2'
      fullPath: '/dashboard2'
      preLoaderRoute: typeof mainDashboard2RouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/api-keys': {
      id: '/(main)/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof mainApiKeysRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/mcps/': {
      id: '/(main)/mcps/'
      path: '/mcps'
      fullPath: '/mcps/'
      preLoaderRoute: typeof mainMcpsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/knowledges/': {
      id: '/(main)/knowledges/'
      path: '/knowledges'
      fullPath: '/knowledges/'
      preLoaderRoute: typeof mainKnowledgesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/agents/': {
      id: '/(main)/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof mainAgentsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/mcps/$id': {
      id: '/(main)/mcps/$id'
      path: '/mcps/$id'
      fullPath: '/mcps/$id'
      preLoaderRoute: typeof mainMcpsIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/agents/$id': {
      id: '/(main)/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof mainAgentsIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainApiKeysRoute: typeof mainApiKeysRoute
  mainDashboard2Route: typeof mainDashboard2Route
  mainLogsRoute: typeof mainLogsRoute
  mainMembersRoute: typeof mainMembersRoute
  mainAgentsIdRoute: typeof mainAgentsIdRoute
  mainMcpsIdRoute: typeof mainMcpsIdRoute
  mainAgentsIndexRoute: typeof mainAgentsIndexRoute
  mainKnowledgesIndexRoute: typeof mainKnowledgesIndexRoute
  mainMcpsIndexRoute: typeof mainMcpsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainApiKeysRoute: mainApiKeysRoute,
  mainDashboard2Route: mainDashboard2Route,
  mainLogsRoute: mainLogsRoute,
  mainMembersRoute: mainMembersRoute,
  mainAgentsIdRoute: mainAgentsIdRoute,
  mainMcpsIdRoute: mainMcpsIdRoute,
  mainAgentsIndexRoute: mainAgentsIndexRoute,
  mainKnowledgesIndexRoute: mainKnowledgesIndexRoute,
  mainMcpsIndexRoute: mainMcpsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
